/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.draksterau.Regenerator.commands;

import com.draksterau.Regenerator.RegeneratorPlugin;
import com.draksterau.Regenerator.config.chunkConfigHandler;
import com.draksterau.Regenerator.config.worldConfigHandler;
import com.draksterau.Regenerator.integration.Integration;
import com.draksterau.Regenerator.tasks.ChunkTask;
import java.util.ArrayList;
import java.util.List;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Chunk;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

/**
 *
 * @author draks
 */
public class regenCommand {
    
    RegeneratorCommand command;
    
    public regenCommand(RegeneratorCommand RegeneratorCommand) {
        this.command = RegeneratorCommand;
    }
    
    public void doCommand() {
        if (command.plugin.getSenderPlayer(command.sender) == null) {
            command.sender.sendMessage(ChatColor.RED + "This command can only be performed while in-game.");
        } else {
            if (!command.plugin.isPaused) {
                Chunk rootChunk = command.plugin.getSenderPlayer(command.sender).getLocation().getChunk();
                worldConfigHandler wConfig = new worldConfigHandler(command.plugin, rootChunk.getWorld());
                chunkConfigHandler cConfig = new chunkConfigHandler(command.plugin, rootChunk);
                if (command.plugin.canManuallyRegen(command.plugin.getSenderPlayer(command.sender), rootChunk)) {
                    Bukkit.getServer().getScheduler().runTask(command.plugin, new ChunkTask(command.plugin, rootChunk));
                    cConfig = new chunkConfigHandler(command.plugin, rootChunk);
                    cConfig.updateLastRegen();
                    Player player = command.plugin.getSenderPlayer(command.sender);
                    Integration integration = command.plugin.getIntegrationForChunk(player.getLocation().getChunk());
                    if (integration != null && integration.isChunkClaimed(rootChunk)) {                    
                        player.sendMessage(command.plugin.getFancyName() + integration.getPlayerRegenReason(player, rootChunk));  
                    } else {
                        player.sendMessage(command.plugin.getFancyName() + ChatColor.GREEN + "The unclaimed area around you has been regenerated.");
                    }
                } else {
                    Chunk senderChunk = command.plugin.getSenderChunk(command.sender);
                    Player player = command.plugin.getSenderPlayer(command.sender);
                    if (!wConfig.getManualRegen()) {
                        player.sendMessage(command.plugin.getFancyName() + ChatColor.RED + "Failed to perform manual regeneration as the world you are on has it disabled.");
                    } else {
                        if (!cConfig.getManualRegen()) {
                            player.sendMessage(command.plugin.getFancyName() + ChatColor.RED + "Failed to perform manual regeneration as the chunk you are in on has it disabled.");
                        } else {
                            if (command.plugin.getCountIntegration(player.getLocation().getChunk()) == 1) {
                                player.sendMessage(command.plugin.getFancyName() + command.plugin.getIntegrationForChunk(senderChunk).getPlayerRegenReason(player, rootChunk));
                                player.sendMessage(command.plugin.getFancyName() + "This requires the permission node: " + command.plugin.getIntegrationForChunk(senderChunk).getPermissionRequiredToRegen(player, rootChunk));
                            } else {
                                if (command.plugin.getCountIntegration(player.getLocation().getChunk()) > 1) {
                                    player.sendMessage(command.plugin.getFancyName() + ChatColor.RED + "This chunk is claimed by more than one grief prevention plugin. It can only be regenerated by OPS or those with the regenerator.regen.override permission node.");
                                } else {
                                    player.sendMessage(command.plugin.getFancyName() + ChatColor.RED + "This chunk is unclaimed and requires the regenerator.regen.unclaimed permission node to regenerate.");
                                }
                            }
                        }
                    }


                }
            } else {
                command.plugin.getSenderPlayer(command.sender).sendMessage(command.plugin.getFancyName() + ChatColor.RED + "Regeneration capabilities have been suspended - TPS has dropped below what is set in configuration.");
            }

        }
    }
}
